### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kevinye-2017** [SBalaSundar/fastapi-crud-app-sample#1]
Successfully post data to cars but get keywords errors. It can be queryed in mysql.

post data example:
```
{
  "manufacturer": "bmw",
  "modelName": "m3",
  "cc": 1,
  "onRoadPrice": 50670,
  "seatingCapacity": 5,
  "gearBox": 1,
  "fuelType": "Diesel"
}
```
curl url:
```
http://localhost:8000/cars
```

erros logs from uvicorn output:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1657, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'Petrol'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/ubuntu/Documents/hsx-admin/fastapi-crud-app-sample/./api.py", line 21, in list_cars
    cars_list = get_all_cars(self.session, limit, offset)
  File "/home/ubuntu/Documents/hsx-admin/fastapi-crud-app-sample/./crud.py", line 10, in get_all_cars
    return session.query(CarInfo).offset(offset).limit(limit).all()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1361, in all
    return self._allrows()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1274, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1686, in _fetchall_impl
    return list(self.iterator)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 392, in <listcomp>
    return [make_row(row) for row in rows]
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1768, in process
    value = self._object_value_for_elem(value)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/enumerated.py", line 94, in _object_value_for_elem
    return super(ENUM, self)._object_value_for_elem(elem)
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1659, in _object_value_for_elem
    util.raise_(
  File "/home/ubuntu/Documents/hsx-admin/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
LookupError: 'Petrol' is not among the defined enum values. Enum name: fueltype. Possible values: petrol, diesel
```

**Comment by Sailokeshg** [comment]
Hey i just encountered the same issue . You just have to change fuel type enum values mentioned in model.py from petrol="Petrol" to Petrol = "Petrol" and the same with diesel.
This should solve the issue.

**Comment by vietanh2000april** [comment]
It's strange that I still got this error when doing POST to /cars
```
LookupError: 'Petrol' is not among the defined enum values. Enum name: fueltype. Possible values: petrol, diesel
```
The database still got updated accordingly with the data in the request body, but I kept getting 500 Internal Server Error. I'm very confused.
